routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['domain' => config('main.selfcare_domain')], function ()
{
    Route::get('/', 'SelfServiceEventController@home')->name('selfcare.event-home');
    Route::get('/{event_code}', 'SelfServiceEventController@index')->name('selfcare.event-form');
});

Route::group(['domain' => config('main.promo_domain')], function ()
{
    Route::get('/', 'PromoPageController@eventNotFound');
    Route::get('/{event_uuid}', 'PromoPageController@index')->name('promopage');
    Route::get('/e/{event_code}', 'PromoPageController@shortLinkRedirect')->name('promopageredirect');
});

Route::get('/', 'HomeController@index')->name('home');
Auth::routes();
Route::group(['domain' => config('main.client_domain'), 'middleware' => ['auth', 'role:Organizer']], function ()
{
    Route::get('/dashboard', 'ClientDashboardController@index')->name('client.dashboard');
    Route::get('/agreement', 'ClientAgreementController@index')->name('client.agreement');
    Route::post('/save-agreement', 'ClientAgreementController@store')->name('client.agreementstore');
    Route::get('/events', 'ClientEventController@index')->name('clientevents.index');
    Route::get('/{uuid}/attendees', 'ClientEventController@attendees')->name('clientevents.attendees');
});
Route::group(['middleware' => ['auth', 'role:Admin']], function ()
{
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('organizers', 'OrganizerController');
    Route::resource('events', 'EventController');
    Route::get('/events/{id}/sms', 'EventController@sms')->name('events.sms');
    Route::post('/events/{id}/sendsms', 'EventController@sendsms')->name('events.sendsms');
    Route::get('/events/{id}/attendees-clockedin', 'EventController@attendees_clockedin')->name('events.attendeesclockedin');
    Route::get('/attendees/import', 'AttendeeController@import')->name('attendees.import');
    Route::post('/attendees/storeimport', 'AttendeeController@storeimport')->name('attendees.storeimport');
    Route::get('/eventguest/import', 'EventGuestController@import')->name('eventguest.import');
    Route::resource('eventguest', 'EventGuestController');
    Route::post('/eventguest/storeimport', 'EventGuestController@storeimport')->name('eventguest.storeimport');
    Route::get('/attendees/export/{event_id}', 'AttendeeController@export')->name('attendees.export');
    Route::get('/attendees/clearall/{event_id}', 'AttendeeController@clearall')->name('attendees.clearall');
    Route::resource('attendees', 'AttendeeController');

});
Route::get('/selfcare/{event_code}', 'SelfServiceEventController@index')->name('selfcare.event-form');

app/User.php
<?php

namespace App;

use Emadadly\LaravelUuid\Uuids;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;
use Yajra\Auditable\AuditableTrait;

class User extends Authenticatable
{
    use Notifiable, HasRoles, AuditableTrait, Uuids, HasApiTokens, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'phone',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use App\User;
use Illuminate\Http\Request;
use Redirect;
//Importing laravel-permission models

//Enables us to output flash messaging
use Spatie\Permission\Models\Role;

class UserController extends Controller
{

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware(['role:' . config('main.admin_role')]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //Get all users and pass it to the view
        $users = User::orderBy('created_at','DESC')->paginate(10);
        return view('users.index')->with('users', $users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //Get all roles and pass it to the view
        $roles = Role::get();
        return view('users.create', ['roles' => $roles]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //Validate name, email and password fields
        $this->validate($request, [
            'name'     => 'required|max:120',
            'email'    => 'required|email|unique:users',
            'password' => 'required|min:6|confirmed',
            'phone'    => 'required',
        ]);
        $request->merge(['password' => bcrypt($request->get('password'))]);

        $user = User::create($request->only(['name', 'email', 'password', 'phone'])); //Retrieving only the email and password data

        $roles = $request['roles']; //Retrieving the roles field
        //Checking if a role was selected
        if (isset($roles))
        {

            foreach ($roles as $role)
            {
                $role_r = Role::where('id', '=', $role)->firstOrFail();
                $user->assignRole($role_r); //Assigning role to user
            }
        }
        //Redirect to the users.index view and display message
        if ($request->filled('back'))
        {
            return Redirect::to($request->input('back'));
        }
        return redirect()->route('users.index')
            ->with('flash_message',
                'User successfully added.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return redirect('users');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user  = User::findOrFail($id); //Get user with specified id
        $roles = Role::get(); //Get all roles

        return view('users.edit', compact('user', 'roles')); //pass user and roles data to view

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $user = User::findOrFail($id); //Get role specified by id

        //Validate name, email and password fields
        $this->validate($request, [
            'name'     => 'required|max:120',
            'email'    => 'required|email|unique:users,email,' . $id,
            'password' => 'nullable|min:6|confirmed',
            'phone'    => 'required',
        ]);

        $input = $request->only(['name', 'email', 'password', 'phone']); //Retreive the name, email and password fields
        if (isset($input['password']))
        {
            $input['password'] = bcrypt($input['password']);
        }
        $roles = $request['roles']; //Retreive all roles
        $user->fill($input)->save();

        if (isset($roles))
        {
            $user->roles()->sync($roles); //If one or more role is selected associate user to roles
        }
        else
        {
            $user->roles()->detach(); //If no role is selected remove exisiting role associated to a user
        }
        return redirect()->route('users.index')
            ->with('flash_message',
                'User successfully edited.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //Find a user with a given id and delete
        $user = User::findOrFail($id);
        $user->delete();

        return redirect()->route('users.index')
            ->with('flash_message',
                'User successfully deleted.');
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
 <div class="page-header">
        <h2>
            Add User
        </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{route('dashboard')}}">
                    Dashboard
                </a>
            </li>
            <li>
                <a href="{{route('users.index')}}">
                    User Administration
                </a>
            </li>
            <li class="active">
                Add User
            </li>
        </ol>
    </div>

     <div class="row clearfix">
        <div class="col-md-6">
            <div class="card">
                <div class="body">
                    <div class="row">
                        <div class="col-md-12">
                                @include('errors.list')
                   {{ Form::open(array('route' => 'users.store')) }}
{{ Form::hidden('back', Request::get('back')) }}
    <div class="form-group">
        {{ Form::label('name', 'Name') }}
        {{ Form::text('name', '', array('class' => 'form-control')) }}
    </div>
    <div class="form-group">
        {{ Form::label('phone', 'Phone', array('class' => 'control-label')) }}
        {{ Form::text('phone', '', array('class' => 'form-control')) }}
    </div>

    <div class="form-group">
        {{ Form::label('email', 'Email') }}
        {{ Form::email('email', '', array('class' => 'form-control')) }}
    </div>

    <div class='form-group'>
        <ul class="list-inline">
        
        @if(Request::get('mode'))
           @foreach ($roles as $role)
           @if(Request::get('mode')==$role->name)
         <li class="eagle-checkbox">
                        <label class="eagle-check custom-checkbox">
             <input type="checkbox" name="roles[]" checked="checked" class="eagle-check-input" value="{{ $role['id']}}" />
            <span class="eagle-check-indicator"></span>
            <span class="eagle-check-description">{{ucfirst($role->name)}}</span>
            </label>
            </li>
            @endif
        @endforeach
        @else
        @foreach ($roles as $role)
         <li class="eagle-checkbox">
                        <label class="eagle-check custom-checkbox">
             <input type="checkbox" name="roles[]" class="eagle-check-input" value="{{ $role['id']}}" />
            <span class="eagle-check-indicator"></span>
            <span class="eagle-check-description">{{ucfirst($role->name)}}</span>
            </label>
            </li>
        @endforeach
        @endif
        
    </ul>
    </div>

    <div class="form-group">
        {{ Form::label('password', 'Password') }}<br>
        {{ Form::password('password', array('class' => 'form-control')) }}

    </div>

    <div class="form-group">
        {{ Form::label('password', 'Confirm Password') }}<br>
        {{ Form::password('password_confirmation', array('class' => 'form-control')) }}

    </div>

    {{ Form::submit('Add', array('class' => 'btn btn-primary  pull-right')) }}

    {{ Form::close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid">
 <div class="page-header">
        <h2>
            Edit User
        </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{route('dashboard')}}">
                    Dashboard
                </a>
            </li>
            <li>
                <a href="{{route('users.index')}}">
                    User Administration
                </a>
            </li>
            <li class="active">
                Edit {{$user->name}}
            </li>
        </ol>
    </div>

     <div class="row clearfix">
        <div class="col-md-6">
            <div class="card">
                <div class="body">
                    <div class="row">
                        <div class="col-md-12">
                                @include('errors.list')
                                {{ Form::model( $user, ['route' => ['users.update', $user->id], 'method' => 'put', 'role' => 'form'] ) }}
                         <div class="form-group">
                          {{ Form::label('name', 'Name') }}
                          {{ Form::text('name', null, array('class' => 'form-control')) }}
                      </div>
                      <div class="form-group">
                          {{ Form::label('phone', 'Phone') }}
                          {{ Form::text('phone', null, array('class' => 'form-control')) }}
                      </div>
                    <div class="form-group">
                        {{ Form::label('email', 'Email') }}
                        {{ Form::email('email', null, array('class' => 'form-control')) }}
                    </div>
                    {{-- <div class="form-group">
                        {{ Form::label('password', 'Confirm Password') }}
                        <br>
                            {{ Form::password('password_confirmation', array('class' => 'form-control')) }}
                        </br>
                    </div> --}}

                <div class="col-md-12">
                    <div class="form-group">
                        <label>
                            Give Role
                        </label>
                    </div>
                    <div class="form-group">
                        
                    <ul class="list-inline">
                        @php
                        $user_roles=$user->roles->pluck('id')->toArray();
                        @endphp
                        @foreach ($roles as $role)
                         <li class="eagle-checkbox">
                                        <label class="eagle-check custom-checkbox">
                             <input type="checkbox" name="roles[]" class="eagle-check-input" value="{{ $role['id']}}" {{(in_array($role['id'],$user_roles))? 'checked':''}} />
                            <span class="eagle-check-indicator"></span>
                            <span class="eagle-check-description">{{ucfirst($role->name)}}</span>
                            </label>
                            </li>
                        @endforeach
                    </ul>   
                    </div>
                </div>
                 {{ Form::submit('Save', array('class' => 'btn btn-primary  pull-right')) }}
                  {{ Form::close() }}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</div>

@endsection

resources/views/users/index.blade.php
@extends('layouts.app')
@section('title'){{'Users - '.config('app.name')}}@endsection
@section('content')
<div class="container-fluid">
 <div class="page-header">
        <h2>
            User Administration 
            <a href="{{route('users.create')}}" class="btn btn-primary"><i class="fa fa-plus" ></i> Add New</a>  
            <a class="btn btn-default" href="{{ route('roles.index') }}">Roles</a>
            <a class="btn btn-default" href="{{ route('permissions.index') }}">Permissions</a>
        </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{route('dashboard')}}">
                    Dashboard
                </a>
            </li>
            <li class="active">
                User Administration
            </li>
        </ol>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-default">
                
                <div class="panel-body">
                     @if(Session::has('flash_message'))
                <div class="alert alert-success"> {!! session('flash_message') !!} </div>
                @endif 
                    @include('errors.list')
                    <div class="row">
                        <div class="col-sm-12 ">
                            <div class="pull-right">{{ $users->links() }}</div>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>
                                        Name
                                    </th>
                                    <th>
                                        Phone
                                    </th>
                                    <th>
                                        Email
                                    </th>
                                    <th>
                                        Date/Time Added
                                    </th>
                                    <th>
                                        Roles
                                    </th>
                                    <th>
                                        Operations
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($users as $user)
                                <tr>
                                    <td>
                                        {{ $user->name }}
                                    </td>
                                    <td>
                                        {{ $user->phone }}
                                    </td>
                                    <td>
                                        {{ $user->email }}
                                    </td>
                                    <td>
                                        {{ $user->created_at->format('F d, Y h:ia') }}
                                    </td>
                                    <td>
                                        {{  $user->roles()->pluck('name')->implode(' ') }}
                                    </td>
                                    {{-- Retrieve array of roles associated to a user and convert to string --}}
                                    <td>
                                        <div class="col-md-* pull-left">
                                            <a class="btn btn-warning pull-left" href="{{ route('users.edit', $user->id) }}" style="margin-right: 3px;">
                                                <i class="fa fa-pencil">
                                                </i>
                                                Edit
                                            </a>
                                        </div>
                                        <div class="col-md-* pull-left">
                                            <form action="{{ route('users.destroy',['id'=>$user->id]) }}" method="post">
                                                {{csrf_field()}}
                                                <input name="_method" type="hidden" value="DELETE"/>
                                                <input name="id" type="hidden" value="{{ $user->id }}">
                                                    <button class="btn btn-danger" type="submit">
                                                        <i class="fa fa-trash">
                                                        </i>
                                                    </button>
                                                </input>
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                         <div class="pull-right">{{ $users->links() }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection