routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['domain' => config('main.selfcare_domain')], function ()
{
    Route::get('/', 'SelfServiceEventController@home')->name('selfcare.event-home');
    Route::get('/{event_code}', 'SelfServiceEventController@index')->name('selfcare.event-form');
});

Route::group(['domain' => config('main.promo_domain')], function ()
{
    Route::get('/', 'PromoPageController@eventNotFound');
    Route::get('/{event_uuid}', 'PromoPageController@index')->name('promopage');
    Route::get('/e/{event_code}', 'PromoPageController@shortLinkRedirect')->name('promopageredirect');
});

Route::get('/', 'HomeController@index')->name('home');
Auth::routes();
Route::group(['domain' => config('main.client_domain'), 'middleware' => ['auth', 'role:Organizer']], function ()
{
    Route::get('/dashboard', 'ClientDashboardController@index')->name('client.dashboard');
    Route::get('/agreement', 'ClientAgreementController@index')->name('client.agreement');
    Route::post('/save-agreement', 'ClientAgreementController@store')->name('client.agreementstore');
    Route::get('/events', 'ClientEventController@index')->name('clientevents.index');
    Route::get('/{uuid}/attendees', 'ClientEventController@attendees')->name('clientevents.attendees');
});
Route::group(['middleware' => ['auth', 'role:Admin']], function ()
{
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('organizers', 'OrganizerController');
    Route::resource('events', 'EventController');
    Route::get('/events/{id}/sms', 'EventController@sms')->name('events.sms');
    Route::post('/events/{id}/sendsms', 'EventController@sendsms')->name('events.sendsms');
    Route::get('/events/{id}/attendees-clockedin', 'EventController@attendees_clockedin')->name('events.attendeesclockedin');
    Route::get('/attendees/import', 'AttendeeController@import')->name('attendees.import');
    Route::post('/attendees/storeimport', 'AttendeeController@storeimport')->name('attendees.storeimport');
    Route::get('/eventguest/import', 'EventGuestController@import')->name('eventguest.import');
    Route::resource('eventguest', 'EventGuestController');
    Route::post('/eventguest/storeimport', 'EventGuestController@storeimport')->name('eventguest.storeimport');
    Route::get('/attendees/export/{event_id}', 'AttendeeController@export')->name('attendees.export');
    Route::get('/attendees/clearall/{event_id}', 'AttendeeController@clearall')->name('attendees.clearall');
    Route::resource('attendees', 'AttendeeController');

});
Route::get('/selfcare/{event_code}', 'SelfServiceEventController@index')->name('selfcare.event-form');

app/Http/Controllers/API/EventController.php
<?php

namespace App\Http\Controllers\API;

use App\Event;
use App\Http\Controllers\Controller;
use App\Http\Resources\EventResource;
use Auth;
use Illuminate\Http\Request;

class EventController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if (!Auth::check())
        {
            return response()->json([
                'status'  => 'error',
                'message' => "You are not authenticated",
            ], 401);
        }
        $event = Event::status()->with('Organizer')->where('event_code', '=', $id)->first();
        if ($event)
        {
            return new EventResource($event);
        }
        else
        {
            return response()->json([
                'status'  => 'error',
                'message' => "Event not found",
            ], 404);
        }

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/EventController.php
<?php

namespace App\Http\Controllers;

use App\Attendee;
use App\AttendeeEvent;
use App\Event;
use App\Events\AttendeeClockedIn;
use App\Organizer;
use App\Services\Event as EventService;
use App\PrintField;
use http\Exception\InvalidArgumentException;
use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Illuminate\Support\Facades\Log;
use Image;
use Shivella\Bitly\Facade\Bitly;
use Storage;
use Symfony\Component\Translation\Exception\InvalidResourceException;

class EventController extends Controller
{
    protected $formRules;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->formRules = [
            'title' => 'required',
            'organizer' => 'required',
        ];
    }

    /**
     * Display a listing of the resource.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $organizer = null;
        if ($request->filled('organizer'))
        {
            $organizer = Organizer::find($request->input('organizer'))->orderBy('created_at','DESC');
        }
        $events = Event::with('Organizer')->withCount(['attendee_event'])->orderBy('created_at','DESC')->filter($request)->paginate(10);
        return view('events.index', compact('events', 'organizer'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        $printFields = PrintField::FIELDS;
        $organizers = Organizer::all();
        return view('events.create', compact('organizers','printFields'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Request $request
     * @return Response
     */
    public function store(EventService $eventService, Request $request)
    {
        $this->validate($request, $this->formRules);
        $event = new Event();
        $event->event_code = $eventService->generateCode();
        $event = $this->eventRecord($event, $request);

        $event->cover_photo = $this->doLogoUpload($request);
        if ($request->hasFile('programme_file'))
        {
            $event->programme_file = $this->programmeUpload($request);
        }
        if ($event->save())
        {
            EventService::savePrintFields($event->id, $request->input('print_fields'));
            try {
                \App\Services\Event::generateShortUrl($event->event_code);
            }
            catch (InvalidResourceException $exception)
            {

            }

            flash('Event was successfully added!')->success();
        }
        else
        {
            flash('Error!')->error();
        }
        return redirect()->route('events.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function show($id)
    {
        $event = Event::with('Organizer', 'attendee_event', 'event_guests')->findOrfail($id);
        if (!$event)
        {
            abort('404');
        }

        $attendees = Attendee::eventattendee($event->id)->where('mode', '=', 'live')->has('Attendance')->get();
        $event_days = EventService::event_days($event->id);
        $attendee_attendances = EventService::atteedee_attendance_days($event->id);
        $event_day_count = count($event_days);

        return view('events.show', compact('event', 'attendees', 'event_days', 'event_day_count', 'attendee_attendances'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $printFields = PrintField::FIELDS;
        $printFieldRecord = PrintField::whereEventId($id)->first() ?? new PrintField();
        $event = Event::with('Organizer')->findOrfail($id);
        $organizers = Organizer::all();
        if (!$event)
        {
            abort('404');
        }
        return view('events.edit', compact('event', 'organizers','printFields','printFieldRecord'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param Request $request
     * @param  int  $id
     * @return Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, $this->formRules);
        $event = Event::findOrfail($id);
        if (!$event)
        {
            abort('404');
        }
        $organizers = Organizer::all();

        $event = $this->eventRecord($event, $request);
        EventService::savePrintFields($id, $request->input('print_fields'));
        if ($request->hasFile('programme_file'))
        {
            $event->programme_file = $this->programmeUpload($request);
        }
        if ($request->hasFile('cover_photo'))
        {
            $event->cover_photo = $this->doLogoUpload($request);
        }

        if ($event->save())
        {
            flash('Event was successfully update!')->success();
        }
        else
        {
            flash('Error!')->error();
        }
        return redirect()->route('events.edit', $event);
    }

    private function eventRecord($event, $request)
    {
        //$event_form_fields= json_decode($request->input('event_form_fields'));
        $event->title = $request->input('title');
        $event->theme = $request->input('theme');
        $event->organizer = $request->input('organizer');
        $event->venue = $request->input('venue');
        $event->excerpt = $request->input('excerpt');
        $event->start_date = $request->input('start_date');
        $event->end_date = $request->input('end_date');
        $event->details = $request->input('event_details');
        $event->background_color = $request->input('background_color');
        $event->font_color = $request->input('font_color');
        $event->programme_file_url = $request->input('programme_file_url');
        $event->app_form_type = ($request->input('app_form_type') === 'on') ? 'pin' : 'input';
        $event->app_field_full_name = ($request->input('app_field_full_name') === 'on') ? 'on' : 'off';
        $event->app_field_phone = ($request->input('app_field_phone') === 'on') ? 'on' : 'off';
        $event->app_field_email = ($request->input('app_field_email') === 'on') ? 'on' : 'off';
        $event->app_field_company = ($request->input('app_field_company') === 'on') ? 'on' : 'off';
        $event->app_field_position = ($request->input('app_field_position') === 'on') ? 'on' : 'off';
        $event->app_field_gender = ($request->input('app_field_gender') === 'on') ? 'on' : 'off';
        $event->app_field_table_number = ($request->input('app_field_table_number') === 'on') ? 'on' : 'off';
        $event->app_field_level_education = ($request->input('app_field_level_education') === 'on') ? 'on' : 'off';
        $event->app_field_age = ($request->input('app_field_age') === 'on') ? 'on' : 'off';
        $event->app_field_location = ($request->input('app_field_location') === 'on') ? 'on' : 'off';
        $event->app_field_country =  ($request->input('app_field_country') === 'on') ? 'on' : 'off';
        $event->app_field_level_education = ($request->input('app_field_level_education') === 'on') ? 'on' : 'off';
        $event->app_field_lived_abroad = ($request->input('app_field_lived_abroad') === 'on') ? 'on' : 'off';
        $event->app_field_attending_as = ($request->input('app_field_attending_as') === 'on') ? 'on' : 'off';
        $event->sms_message = $request->input('sms_message');
        $event->tag_image_option = $request->input('tag_image_option');

        return $event;
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        $event = Event::findOrfail($id);
        if ($event->delete())
        {
            flash('Event was successfully deleted!')->success();
        }
        else
        {
            flash('Error!')->error();
        }
        return redirect()->route('events.index');
    }

    public function doLogoUpload($request)
    {
        if ($request->hasFile('cover_photo'))
        {
            //Storage::makeDirectory(public_path() . '/' . config('main.cover_photo_dir'));
            $photoPath = public_path() . '/' . config('main.cover_photo_dir');
            $path = $request->cover_photo->path();
            $extension = $request->cover_photo->extension();
            $originalName = $request->cover_photo->getClientOriginalName();
            $filesize = $request->cover_photo->getClientSize();
            $mime_type = $request->cover_photo->getClientMimeType();

            $filename = uniqid() . '.' . $extension;

            //Generate width 100 photo file
            $img = Image::make($request->cover_photo->getRealPath());
            $img->save($photoPath . DIRECTORY_SEPARATOR . $filename);
            $media_width = $img->width();
            $media_height = $img->height();
            //$img->fit(100);
            $img->resize(100, 100, function ($constraint)
            {
                $constraint->aspectRatio();
                //$constraint->upsize();
            });
            $img->save($photoPath . DIRECTORY_SEPARATOR . '100.' . $filename);

            //Generate width 300 photo file
            $img = Image::make($request->cover_photo->getRealPath());
            //$img->crop(340, 200);
            //$img->insert(public_path('images/logo.png'));
            $img->resize(320, null, function ($constraint)
            {
                $constraint->aspectRatio();
                //$constraint->upsize();
            });
            $img->save($photoPath . DIRECTORY_SEPARATOR . 'medium.' . $filename);

            return $filename;
        }
        return null;
    }

    protected function programmeUpload($request)
    {
        if ($request->hasFile('programme_file'))
        {

resources/views/events/create.blade.php
@extends('layouts.app')
@section('title'){{'Events - Add New - '.config('app.name')}}@endsection
@section('content')
<div class="container-fluid">
    <div class="page-header">
        <h2>
            Events - Add New
        </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{route('dashboard')}}">
                    Dashboard
                </a>
            </li>
             <li>
                <a href="{{route('events.index')}}">
                    Events
                </a>
            </li>
            <li class="active">
                Add New
            </li>
        </ol>
    </div>
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="card">
                <div class="body">
                    <div class="row">
                        <form action="{{route('events.store')}}" class="" enctype="multipart/form-data" method="POST">
                            @include('events.form',['mainDataCollection'=>null])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/events/edit.blade.php
@extends('layouts.app')
@section('title'){{$event->title.' - Events -  '.config('app.name')}}@endsection
@section('content')
<div class="container-fluid">
    <div class="page-header">
        <h2>
            Event - Edit [{{$event->title}}]
        </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{route('dashboard')}}">
                    Dashboard
                </a>
            </li>
             <li>
                <a href="{{route('events.index')}}">
                    Events
                </a>
            </li>
            <li class="active">
                {{$event->title}}
            </li>
        </ol>
    </div>
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="card">
                <div class="body">
                    <div class="row">
                        <form action="{{route('events.update',['id'=>$event->id])}}" class="" enctype="multipart/form-data" method="POST">
                            <input type="hidden" name="_method" value="PUT">
                            @include('events.form',['organizer_id'=>$event->organizer])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/events/index.blade.php
@extends('layouts.app')
@section('title'){{'Events - '.config('app.name')}}@endsection
@section('content')
<div class="container-fluid">
    <div class="page-header">
        <h2>
            Events <a href="{{route('events.create')}}" class="btn btn-primary"><i class="fa fa-plus" ></i> Add New</a>
        </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{route('dashboard')}}">
                    Dashboard
                </a>
            </li>
            <li class="active">
                Events
            </li>
        </ol>
    </div>
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="card">
                @if($organizer)
                    <div class="card-header">
                        <h2>
                            {{$organizer->name.' - Events'}}
                        </h2>
                    </div>
                @endif
                <div class="body">
                    @include('flash::message')
                    <div class="row">

                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        Code
                                    </th>
                                    <th>
                                        Title
                                    </th>

                                    <th>
                                        Organizer
                                    </th>
                                    <th>
                                        No. of Attendees
                                    </th>
                                    <th>
                                        Start Date
                                    </th>
                                    <th colspan="5">

                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($events as $event)

                                <tr>
                                    <td>
                                        {{$event['event_code']}} {!! ($event['short_url']) ? '<a href="'. $event['short_url'] .'" title="'.$event['short_url'].'" target="_blank"><i class="fa fa-external-link fa-lg"></i></a>' : ''   !!}
                                    </td>
                                    <td>
                                        <a href="{{ route('events.edit',$event->id) }}"> {{$event['title']}}</a>
                                    </td>
                                    <td>
                                        <a href="{{route('organizers.show',$event->organizer)}}">{{$event->Organizer->name ?? null}}</a>
                                    </td>
                                    <td>
                                        {{ $event->attendee_event_count ?? 'N/A'}}
                                    </td>
                                    <td>
                                        {{($event->start_date)? $event->start_date->format('d M ,Y') : 'N/A'}}
                                    </td>


                                    <td>
                                        <a class="btn btn-default" href="{{ route('events.show',$event->id) }}" title="View">
                                            <i class="fa fa-eye"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <a class="btn btn-success" href="{{ route('attendees.index', ['event'=>$event->id]) }}" title="Attendees">
                                            <i class="fa fa-group"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <a class="btn" href="{{ route('eventguest.index', ['event'=>$event->id]) }}" title="Show Event Guests">
                                            <i class="fa fa-user fa-lg"></i>
                                        </a>
                                    </td>
                                     <td>
                                        <a class="btn btn-info" href="{{ route('events.sms', ['event'=>$event->id]) }}" title="Send SMS">
                                            <i class="fa fa-mobile fa-lg"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <a class="btn btn-warning" href="{{ route('events.edit',$event->id) }}" title="Edit">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <form action="{{ route('events.destroy',['id'=>$event->id]) }}" method="post">
                                            @csrf
                                            <input name="_method" type="hidden" value="DELETE">
                                                 <button class="btn btn-danger" type="submit" title="Delete">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </input>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div class="col-md-12">
                            Showing {{($events->currentpage()-1)* $events->perpage()+1}} to {{(($events->currentpage()-1) * $events->perpage())+$events->count()}} of {{$events->total()}} entries
                        </div>
                        <div class="pull-right">{{ $events->links() }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/events/sms.blade.php
@extends('layouts.app')
@section('title'){{'Send Event SMS - '.$event->title.' - '.config('app.name')}}@endsection
@section('content')
<div class="container-fluid">
    <div class="page-header">
        <h2>
            Send Event SMS - [{{$event->title}}]
        </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{route('dashboard')}}">
                    Dashboard
                </a>
            </li>
             <li>
                <a href="{{route('events.index')}}">
                    Send Event SMS
                </a>
            </li>
            <li class="active">
                {{$event->title}}
            </li>
        </ol>
    </div>
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="card">
                <div class="body">
                    <div class="row">
                        <div class="clearfix">
                            <ul class="list-inline">
                                <li> <a class="btn btn-default" href="{{ route('events.show',$event->id) }}">
                                        <i class="fa fa-eye"></i> Event Details
                                    </a>
                                </li>
                                <li>
                                    <a class="btn btn-success " href="{{route('promopage',$event->uuid)}}" target="_blank">
                                        <i class="fa fa-external-link"></i> Goto Promo Page
                                    </a>
                                </li>
                            </ul>
                           
                            
                        </div>
                        <div class="col-md-6">
                            <dl class="dl-vertical showview">
                                <dt>
                                    Attendee Total
                                </dt>
                                <dd>
                                    {{($event->attendee_event->count()) ?? 'N/A'}}
                                </dd>
                                <dt>
                                    Organizer
                                </dt>
                                <dd>
                                    {{$event->Organizer->name}}
                                </dd>
                               
                            </dl>
                        </div>
                        <div class="col-md-6">
                            <form action="{{route('events.sendsms',['id'=>$event->id])}}" method="POST">
                            {{csrf_field()}}
                            <div class="form-group{{ $errors->has('sms_message') ? ' has-error' : '' }}">
                                <label class=" control-label" for="event_sms_message">
                                    SMS Message
                                </label>
                                <textarea  class="form-control" id="event_sms_message" name="sms_message" placeholder="Event SMS Message" rows="5">{{ old('sms_message',$event->sms_message ?? null ) }}</textarea>
                                 <small>{!! __('Use <code>[EVENT_TITLE]</code> code as Event Title value, <code>[EVENT_LINK]</code> code as Event Page Link value and <code>[ATTENDEE_PIN_CODE]</code> code as Attendee PIN Code ') !!}</small>
                                <small><strong>Hint:</strong> The square bracket blocks will be automatically replaced with the appropraite content when SMS is sent.</small>
                                @if ($errors->has('excerpt'))
                                <span class="help-block">
                                    <strong>
                                        {{ $errors->first('sms_message') }}
                                    </strong>
                                </span>
                                @endif
                            </div>
                            
                             <div class="form-group">
                                <input class="btn btn-primary pull-right" name="submit" type="submit" value="Send"/>
                            </div>
                            </form>
                        </div>
                        <div class="clearfix"></div>
                       
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection