routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['domain' => config('main.selfcare_domain')], function ()
{
    Route::get('/', 'SelfServiceEventController@home')->name('selfcare.event-home');
    Route::get('/{event_code}', 'SelfServiceEventController@index')->name('selfcare.event-form');
});

Route::group(['domain' => config('main.promo_domain')], function ()
{
    Route::get('/', 'PromoPageController@eventNotFound');
    Route::get('/{event_uuid}', 'PromoPageController@index')->name('promopage');
    Route::get('/e/{event_code}', 'PromoPageController@shortLinkRedirect')->name('promopageredirect');
});

Route::get('/', 'HomeController@index')->name('home');
Auth::routes();
Route::group(['domain' => config('main.client_domain'), 'middleware' => ['auth', 'role:Organizer']], function ()
{
    Route::get('/dashboard', 'ClientDashboardController@index')->name('client.dashboard');
    Route::get('/agreement', 'ClientAgreementController@index')->name('client.agreement');
    Route::post('/save-agreement', 'ClientAgreementController@store')->name('client.agreementstore');
    Route::get('/events', 'ClientEventController@index')->name('clientevents.index');
    Route::get('/{uuid}/attendees', 'ClientEventController@attendees')->name('clientevents.attendees');
});
Route::group(['middleware' => ['auth', 'role:Admin']], function ()
{
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('organizers', 'OrganizerController');
    Route::resource('events', 'EventController');
    Route::get('/events/{id}/sms', 'EventController@sms')->name('events.sms');
    Route::post('/events/{id}/sendsms', 'EventController@sendsms')->name('events.sendsms');
    Route::get('/events/{id}/attendees-clockedin', 'EventController@attendees_clockedin')->name('events.attendeesclockedin');
    Route::get('/attendees/import', 'AttendeeController@import')->name('attendees.import');
    Route::post('/attendees/storeimport', 'AttendeeController@storeimport')->name('attendees.storeimport');
    Route::get('/eventguest/import', 'EventGuestController@import')->name('eventguest.import');
    Route::resource('eventguest', 'EventGuestController');
    Route::post('/eventguest/storeimport', 'EventGuestController@storeimport')->name('eventguest.storeimport');
    Route::get('/attendees/export/{event_id}', 'AttendeeController@export')->name('attendees.export');
    Route::get('/attendees/clearall/{event_id}', 'AttendeeController@clearall')->name('attendees.clearall');
    Route::resource('attendees', 'AttendeeController');

});
Route::get('/selfcare/{event_code}', 'SelfServiceEventController@index')->name('selfcare.event-form');

app/Organizer.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Yajra\Auditable\AuditableTrait;
use Emadadly\LaravelUuid\Uuids;
class Organizer extends Model
{
    use SoftDeletes, AuditableTrait, Uuids;
    protected $table    = 'organizers';
    protected $fillable = ['name', 'email', 'phone', 'status', 'website', 'address', 'logo_filename'];
}

app/Http/Controllers/OrganizerController.php
<?php

namespace App\Http\Controllers;

use App\Organizer;
use App\User;
use Illuminate\Http\Request;
use Image;
use Redirect;
use Storage;

class OrganizerController extends Controller
{

    protected $formRules;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->formRules = [
            'name' => 'required',
        ];
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $organizers = Organizer::orderBy('created_at','DESC')->paginate(10);
        return view('organizers.index', compact('organizers'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $accounts = User::role('Organizer')->get();
        return view('organizers.create', compact('accounts'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, $this->formRules);
        $organizer                = new Organizer();
        $organizer->account       = $request->input('account');
        $organizer->name          = $request->input('name');
        $organizer->email         = $request->input('email');
        $organizer->phone         = $request->input('phone');
        $organizer->status        = $request->input('status');
        $organizer->address       = $request->input('address');
        $organizer->website       = $request->input('website');
        $organizer->logo_filename = $this->doLogoUpload($request);
        $organizer->save();

        if ($organizer->save())
        {
            flash('Organizer was successfully added!')->success();
        }
        else
        {
            flash('Error!')->error();
        }

        if ($request->filled('back'))
        {
            return Redirect::to($request->input('back'));
        }
        return redirect()->route('organizers.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $organizer = Organizer::findOrfail($id);
        if (!$organizer)
        {
            abort('404');
        }
        return view('organizers.show', compact('organizer'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $organizer = Organizer::findOrfail($id);
        $accounts  = User::role('Organizer')->get();
        if (!$organizer)
        {
            abort('404');
        }
        return view('organizers.edit', compact('organizer', 'accounts'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, $this->formRules);
        $organizer          = Organizer::find($id);
        $organizer->account = $request->input('account');
        $organizer->name    = $request->input('name');
        $organizer->email   = $request->input('email');
        $organizer->phone   = $request->input('phone');
        $organizer->status  = $request->input('status');
        $organizer->website = $request->input('website');
        $organizer->address = $request->input('address');
        if ($request->hasFile('logo_filename'))
        {
            $organizer->logo_filename = $this->doLogoUpload($request);
        }

        if ($organizer->save())
        {
            flash('Organizer was successfully updated!')->success();
        }
        else
        {
            flash('Error!')->error();
        }
        return redirect()->route('organizers.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $organizer = Organizer::findOrfail($id);
        if ($organizer->delete())
        {
            flash('Organizer was successfully deleted!')->success();
        }
        else
        {
            flash('Error!')->error();
        }
        return redirect()->route('organizers.index');
    }

    public function doLogoUpload($request)
    {
        if ($request->hasFile('logo_filename'))
        {
            //Storage::makeDirectory(public_path() . '/' . config('main.organizer_logo_dir'));
            $photoPath    = public_path() . '/' . config('main.organizer_logo_dir');
            $path         = $request->logo_filename->path();
            $extension    = $request->logo_filename->extension();
            $originalName = $request->logo_filename->getClientOriginalName();
            $filesize     = $request->logo_filename->getClientSize();
            $mime_type    = $request->logo_filename->getClientMimeType();

            $filename = uniqid() . '.' . $extension;

            //Generate width 100 photo file
            $img = Image::make($request->logo_filename->getRealPath());
            $img->save($photoPath . DIRECTORY_SEPARATOR . $filename);
            $media_width  = $img->width();
            $media_height = $img->height();
            //$img->fit(100);
            $img->resize(100, 100, function ($constraint)
            {
                $constraint->aspectRatio();
                //$constraint->upsize();
            });
            $img->save($photoPath . DIRECTORY_SEPARATOR . '100.' . $filename);

            //Generate width 300 photo file
            $img = Image::make($request->logo_filename->getRealPath());
            //$img->crop(340, 200);
            //$img->insert(public_path('images/logo.png'));
            $img->resize(320, null, function ($constraint)
            {
                $constraint->aspectRatio();
                //$constraint->upsize();
            });
            $img->save($photoPath . DIRECTORY_SEPARATOR . 'medium.' . $filename);

            return $filename;
        }
        return null;
    }
}

resources/views/organizers/create.blade.php
@extends('layouts.app')
@section('title'){{'Organizers - Add New - '.config('app.name')}}@endsection
@section('content')
<div class="container-fluid">
    <div class="page-header">
        <h2>
            Organizers - Add New
        </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{route('dashboard')}}">
                    Dashboard
                </a>
            </li>
            <li>
                <a href="{{route('organizers.index')}}">
                    Organizers
                </a>
            </li>
            <li class="active">
                Add New
            </li>
        </ol>
    </div>
    <div class="row clearfix">
        <div class="col-md-6">
            <div class="card">
                <div class="body">
                    <div class="row">
                        <form action="{{route('organizers.store')}}" class="" enctype="multipart/form-data" method="POST">
                            <input type="hidden" name="back" value="{{ Request::get('back') }}">
                            @include('organizers.form',['organizer_id'=>null])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/organizers/edit.blade.php
@extends('layouts.app')
@section('title'){{$organizer->name.' - Organizers - '.config('app.name')}}@endsection
@section('content')
<div class="container-fluid">
    <div class="page-header">
        <h2>
            Organizers - Edit [#{{$organizer->id}}]
        </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{route('dashboard')}}">
                    Dashboard
                </a>
            </li>
            <li class="active">
                {{$organizer->name}}
            </li>
        </ol>
    </div>
    <div class="row clearfix">
        <div class="col-md-6">
            <div class="card">
                <div class="body">
                    <div class="row">
                        <form action="{{route('organizers.update',['id'=>$organizer->id])}}" class="" enctype="multipart/form-data" method="POST">
                            <input type="hidden" name="_method" value="PUT">
                            @include('organizers.form',['organizer_id'=>$organizer->id,'account_id'=>$organizer->account])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/organizers/form.blade.php
{{csrf_field()}}
 @include('partials.organizeraccount-select')
<div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
    <label class=" control-label" for="name">
        Name
    </label>
    <input autofocus="" class="form-control" id="name" name="name" placeholder="Organizer Name" type="text" value="{{ old('name',$organizer->name ?? null ) }}"/>
    @if ($errors->has('name'))
    <span class="help-block">
        <strong>
            {{ $errors->first('name') }}
        </strong>
    </span>
    @endif
</div>
<div class="form-group{{ $errors->has('phone') ? ' has-error' : '' }}">
    <label class=" control-label" for="name">
        Phone Number
    </label>
    <input class="form-control" id="phone" name="phone" placeholder="Organizer Phone Number" type="text" value="{{ old('phone',$organizer->phone ?? null ) }}"/>
    @if ($errors->has('phone'))
    <span class="help-block">
        <strong>
            {{ $errors->first('phone') }}
        </strong>
    </span>
    @endif
</div>
<div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
    <label class=" control-label" for="name">
        Email
    </label>
    <input class="form-control" id="email" name="email" placeholder="Organizer Email" type="email" value="{{ old('email',$organizer->email ?? null ) }}"/>
    @if ($errors->has('email'))
    <span class="help-block">
        <strong>
            {{ $errors->first('email') }}
        </strong>
    </span>
    @endif
</div>
<div class="form-group{{ $errors->has('website') ? ' has-error' : '' }}">
    <label class=" control-label" for="website">
        Website
    </label>
    <input class="form-control" id="website" name="website" placeholder="Organizer Website" type="text" value="{{ old('website',$organizer->website ?? null ) }}"/>
    @if ($errors->has('website'))
    <span class="help-block">
        <strong>
            {{ $errors->first('website') }}
        </strong>
    </span>
    @endif
</div>
<div class="form-group{{ $errors->has('address') ? ' has-error' : '' }}">
    <label class=" control-label" for="address">
        Address
    </label>
    <textarea  class="form-control" id="address" name="address" placeholder="Organizer Address">{{ old('address',$organizer->address ?? null ) }}</textarea>
    @if ($errors->has('address'))
    <span class="help-block">
        <strong>
            {{ $errors->first('address') }}
        </strong>
    </span>
    @endif
</div>
<div class="form-group{{ $errors->has('status') ? ' has-error' : '' }}">
    <label class=" control-label" for="name">
        Status
    </label>
    @php
        $organizer_active_status=((isset($organizer->status) && $organizer->status=='active') || !isset($organizer->status) )? ' checked':'';
        $organizer_inactive_status=((isset($organizer->status)) && $organizer->status=='inactive')? ' checked':'';
    @endphp
    <input class="with-gap" id="status_active" name="status" type="radio" value="active" {{$organizer_active_status}}/>
    <label for="status_active">
        Active
    </label>
    <input class="with-gap" id="status_inactive" name="status" type="radio" value="inactive" {{$organizer_inactive_status}} />
    <label class="m-l-20" for="status_inactive">
        Inactive
    </label>
    <span class="help-block">
        <strong>
            {{ $errors->first('status') }}
        </strong>
    </span>
</div>
<div class="form-group{{ $errors->has('logo_filename') ? ' has-error' : '' }} ">
    <div class="fileinput fileinput-new" data-provides="fileinput">
        <div class="fileinput-preview thumbnail" data-trigger="fileinput" style="width: 200px; height: 150px;">
             @if(isset($organizer->logo_filename))
            <img alt="Logo" height="auto" id="photo_preview" onerror="this.src='{{asset('photos/nophoto.jpg')}}'" src="{{ asset(config('main.organizer_logo_dir').'/medium.'.$organizer->logo_filename )}}"  />
            @endif

        </div>
        <div>
            <span class="btn btn-info btn-file"><span class="fileinput-new">Select Logo</span>
            <span class="fileinput-exists">Change</span><input accept="image/gif, image/jpg, image/jpeg, image/png" class="form-control" name="logo_filename"  type="file"></span>
            <a href="#" class="btn btn-default bg-red fileinput-exists" data-dismiss="fileinput">Remove</a>
        </div>
        @if ($errors->has('logo_filename'))
            <span class="help-block">
                <strong>
                    {{ $errors->first('logo_filename') }}
                </strong>
            </span>
        @endif
    </div>
</div>



<div class="form-group">
    <input class="btn btn-primary pull-right" name="submit" type="submit" value="Submit"/>
</div>

resources/views/organizers/index.blade.php
@extends('layouts.app')
@section('title'){{'Organizers - '.config('app.name')}}@endsection
@section('content')
<div class="container-fluid">
    <div class="page-header">
        <h2>
            Organizers <a href="{{route('organizers.create')}}" class="btn btn-primary"><i class="fa fa-plus" ></i> Add New</a>
        </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{route('dashboard')}}">
                    Dashboard
                </a>
            </li>
            <li class="active">
                Organizers
            </li>
        </ol>
    </div>
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="card">
                <div class="body">
                    @include('flash::message')
                    <div class="row">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        ID
                                    </th>
                                    <th>
                                        Name
                                    </th>
                                    
                                    <th>
                                        Email
                                    </th>
                                    <th>
                                        Phone Number
                                    </th>
                                    <th>
                                        Created
                                    </th>
                                    <th colspan="4">
                                        Action
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($organizers as $organizer)
      
                                <tr>
                                    <td>
                                        {{$organizer['id']}}
                                    </td>
                                    <td>
                                        {{$organizer['name']}}
                                    </td>
                                    <td>
                                        {{$organizer['email'] ?? 'N/A'}}
                                    </td>
                                    <td>
                                        {{$organizer['phone'] ?? 'N/A'}}
                                    </td>
                                    <td>
                                        {{$organizer->created_at->format('d M ,Y h:ia')}}
                                    </td>
                                     <td>
                                        <a class="btn btn-success" href="{{ route('events.index', ['organizer'=>$organizer->id]) }}" title="Events">
                                            <i class="fa fa-calendar"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <a class="btn btn-default" href="{{ route('organizers.show', $organizer->id) }}" title="View">
                                            <i class="fa fa-eye"></i>
                                        </a>
                                    </td>
                                    <td>
                                        <a class="btn btn-warning" href="{{ route('organizers.edit',$organizer->id) }}" title="Edit">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    </td>

                                    <td>
                                        <form action="{{ route('organizers.destroy',['id'=>$organizer->id]) }}" method="post">
                                            @csrf
                                            <input name="_method" type="hidden" value="DELETE">
                                                <button class="btn btn-danger" type="submit" title="Delete">
                                                    <i class="fa fa-trash"></i>
                                                </button>
                                            </input>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        <div class="col-md-12">
                            Showing {{($organizers->currentpage()-1)* $organizers->perpage()+1}} to {{(($organizers->currentpage()-1) * $organizers->perpage())+$organizers->count()}} of {{$organizers->total()}} entries
                        </div>
                        <div class="pull-right">{{ $organizers->links() }}</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/organizers/show.blade.php
@extends('layouts.app')
@section('title'){{$organizer->name.' - Organizers - '.config('app.name')}}@endsection
@section('content')
<div class="container-fluid">
    <div class="page-header">
        <h2>
            Organizers - View [#{{$organizer->id}}]
        </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{route('dashboard')}}">
                    Dashboard
                </a>
            </li>
            <li>
                <a href="{{route('organizers.index')}}">
                    Organizers
                </a>
            </li>
            <li class="active">
                {{$organizer->name}}
            </li>
        </ol>
    </div>
    <div class="row clearfix">
        <div class="col-md-6">
            <div class="card">
                <div class="body">
                    <div class="row">
                        <dl class="dl-vertical showview">
                            <dt>Name</dt>
                            <dd>{{$organizer->name}}</dd>
                            <dt>Email</dt>
                            <dd>{{$organizer['email'] ?? 'N/A'}}</dd>
                            <dt>Phone</dt>
                            <dd>{{$organizer['phone'] ?? 'N/A'}}</dd>
                            <dt>Website</dt>
                            <dd>{{$organizer['website'] ?? 'N/A'}}</dd>
                            <dt>Address</dt>
                            <dd>{{$organizer['address'] ?? 'N/A'}}</dd>
                            <dt>Status</dt>
                            <dd>{{ucwords($organizer['status']) ?? 'N/A'}}</dd>
                            <dt>Created</dt>
                            <dd>{{$organizer->created_at->format('j, M Y')}}</dd>
                            <dt>Logo</dt>
                            <dd>
                                @if(isset($organizer->logo_filename))
                                <div class="fileinput-preview thumbnail col-md-3">
                                    <img alt="Logo" height="auto" id="photo_preview" onerror="this.src='{{asset('photos/nophoto.jpg')}}'" src="{{ asset(config('main.organizer_logo_dir').'/medium.'.$organizer->logo_filename )}}"  />
                                </div>
                                @endif
                            </dd>
                        </dl>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection