routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::group(['domain' => config('main.selfcare_domain')], function ()
{
    Route::get('/', 'SelfServiceEventController@home')->name('selfcare.event-home');
    Route::get('/{event_code}', 'SelfServiceEventController@index')->name('selfcare.event-form');
});

Route::group(['domain' => config('main.promo_domain')], function ()
{
    Route::get('/', 'PromoPageController@eventNotFound');
    Route::get('/{event_uuid}', 'PromoPageController@index')->name('promopage');
    Route::get('/e/{event_code}', 'PromoPageController@shortLinkRedirect')->name('promopageredirect');
});

Route::get('/', 'HomeController@index')->name('home');
Auth::routes();
Route::group(['domain' => config('main.client_domain'), 'middleware' => ['auth', 'role:Organizer']], function ()
{
    Route::get('/dashboard', 'ClientDashboardController@index')->name('client.dashboard');
    Route::get('/agreement', 'ClientAgreementController@index')->name('client.agreement');
    Route::post('/save-agreement', 'ClientAgreementController@store')->name('client.agreementstore');
    Route::get('/events', 'ClientEventController@index')->name('clientevents.index');
    Route::get('/{uuid}/attendees', 'ClientEventController@attendees')->name('clientevents.attendees');
});
Route::group(['middleware' => ['auth', 'role:Admin']], function ()
{
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
    Route::resource('users', 'UserController');
    Route::resource('roles', 'RoleController');
    Route::resource('permissions', 'PermissionController');
    Route::get('/dashboard', 'DashboardController@index')->name('dashboard');
    Route::resource('organizers', 'OrganizerController');
    Route::resource('events', 'EventController');
    Route::get('/events/{id}/sms', 'EventController@sms')->name('events.sms');
    Route::post('/events/{id}/sendsms', 'EventController@sendsms')->name('events.sendsms');
    Route::get('/events/{id}/attendees-clockedin', 'EventController@attendees_clockedin')->name('events.attendeesclockedin');
    Route::get('/attendees/import', 'AttendeeController@import')->name('attendees.import');
    Route::post('/attendees/storeimport', 'AttendeeController@storeimport')->name('attendees.storeimport');
    Route::get('/eventguest/import', 'EventGuestController@import')->name('eventguest.import');
    Route::resource('eventguest', 'EventGuestController');
    Route::post('/eventguest/storeimport', 'EventGuestController@storeimport')->name('eventguest.storeimport');
    Route::get('/attendees/export/{event_id}', 'AttendeeController@export')->name('attendees.export');
    Route::get('/attendees/clearall/{event_id}', 'AttendeeController@clearall')->name('attendees.clearall');
    Route::resource('attendees', 'AttendeeController');

});
Route::get('/selfcare/{event_code}', 'SelfServiceEventController@index')->name('selfcare.event-form');

app/Attendee.php
<?php

namespace App;

use Emadadly\LaravelUuid\Uuids;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Ramsey\Uuid\Uuid;
use Yajra\Auditable\AuditableTrait;

class Attendee extends Model
{
    use SoftDeletes, AuditableTrait, Uuids;
    protected $table = 'attendees';
    protected $guarded = [];
    //protected $fillable = ['full_name', 'uuid', 'event', 'phone', 'email', 'company', 'position', 'mode', 'gender', 'registration', 'status', 'pin_code', 'table_number', 'age', 'location', 'level_education', 'lived_abroad', 'attending_as'];
    public $incrementing = false;
    protected $primaryKey = 'id';

    public static function boot()
    {
        parent::boot();
        self::creating(function($model){
            $model->id = Uuid::uuid4()->toString();
        });
    }

    public function Event()
    {
        return $this->belongsTo('App\Event', 'event', 'id');
    }

    public function guest()
    {
        return $this->belongsTo('App\EventGuest', 'attendee_id', 'id');
    }

    public function attendee_event()
    {
        return $this->belongsTo('App\AttendeeEvent', 'id', 'attendee_id');
    }

    public function Attendance()
    {
        return $this->hasMany('App\Attendance', 'attendee_id', 'id');
    }

    public function scopeFilter($query, $request)
    {
        if ($request->filled('event'))
        {
            $event = $request->input('event');
            $query->where('event', '=', $event);
        }

        if ($request->has('search') && $request->filled('search'))
        {
            $search = $request->input('search');
            $terms = explode(' ', $search);
            $query->where(function ($query) use ($terms)
            {
                if ($terms)
                {
                    foreach ($terms as $term)
                    {
                        $query->orWhere('full_name', 'like', '%' . $term . '%');
                    }
                }

            });
        }
        return $query;
    }

    public function scopeEventAttendee($query, $event_id)
    {
        return $query->whereHas('attendee_event', function ($query) use ($event_id)
        {
            $query->where('attendee_events.event_id', '=', $event_id);
        });

    }

}

app/Http/Controllers/API/AttendeeController.php
<?php

namespace App\Http\Controllers\API;

use App\Attendance;
use App\Attendee;
use App\AttendeeEvent;
use App\Event;
use App\EventGuest;
use App\EventGuestAttendee;
use App\Events\AttendeeClockedIn;
use App\Events\PrintTag;
use App\Http\Controllers\Controller;
use App\Http\Resources\AttendeeCollection;
use App\Services\AttendeeService;
use App\Services\Event as EventService;
use App\Services\PinCode;
use Carbon\Carbon;
use Illuminate\Http\Request;
use SimpleSoftwareIO\QrCode\BaconQrCodeGenerator;
use Storage;
use Validator;
use Log;
class AttendeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     * @param  $pinCode
     */
    public function store(PinCode $pinCode, Request $request)
    {
        $printNewTag = true;
        $otherData = [];
        $otherData['table_number'] = null;
        $otherData['attendee'] = null;
        $request = $request->merge($this->fixNull($request->input()));
        Log::info(print_r($request->input(), true));
        $registration = $request->input('registration');
        $otherData['location'] = '';

        $otherData['location_to_country'] = ($request->has('location_to_country'))? $request->input('location_to_country') : 'off';
        if ($registration == 'pin')
        {
            $validator = Validator::make($request->all(), [
                'pin_code' => 'required|max:4',
            ]);
        }
        else
        {
            if ($request->input('guest_show') == 'off')
            {
                $validator = Validator::make($request->all(), [
                    'full_name' => 'required|min:2|max:255',
                    /*'phone' => 'required|regex:/[0-9]{10,15}/|digits_between:10,15',*/
                ]);
            }
        }

        if ($request->input('guest_show') == 'off')
        {
            if ($validator->fails())
            {
                return response()->json([
                    'status' => 'error',
                    'message' => $validator->errors()->all(),
                ], 400);
            }
        }
        Log::debug(print_r($request->input(), true));
        //Verify pin from app
        if ($registration == 'pin')
        {
            $pin_code = $request->input('pin_code');
            $event_code = $request->input('event_code');
            $event = Event::where('event_code', '=', $event_code)->first();
            $attendeeEvent = $pinCode->verifyAttendeeEvent($pin_code, $event->id);
            if (!$attendeeEvent)
            {
                return response()->json([
                    'status' => 'error',
                    'message' => 'Invalid Pin',
                ], 400);
            }
            $event = ($attendeeEvent->event) ? $attendeeEvent->event : null;
            $attendee = ($attendeeEvent->attendee) ? $attendeeEvent->attendee : null;
            if ($request->has('lived_abroad') && $request->filled('lived_abroad'))
            {
                $attendee->lived_abroad = $request->input('lived_abroad');
                $attendee->save();
            }

            if( $event && $event->tag_image_option == 'qr_code') {
                AttendeeService::generateQRCode($event, $attendee, $pin_code);
            }
        }
        else
        {
            $event_code = $request->input('event_code');
            $event = Event::where('event_code', '=', $event_code)->first();
            $pin_code = $pinCode->generate($event->id);
            $attendee = Attendee::where('email', '=', $request->input('email'))->where('phone', '=', $request->input('phone'))->where('full_name', '=', $request->input('full_name'))->where('company', '=', $request->input('company'))->where('gender', '=', $request->input('gender'))->where('table_number', '=', $request->input('table_number'))->where('mode', '=', $request->input('mode'))->where('country', '=', $request->input('country'))->where('position', '=', $request->input('position'))->where('age', '=', $request->input('age'))->where('level_education', '=', $request->input('level_education'))->where('location', '=', $request->input('location'))->where('attending_as', '=', $request->input('attending_as'))->where('lived_abroad', '=', $request->input('lived_abroad'))->whereDate('created_at', Carbon::today())->orderBy('created_at', 'DESC')->first();
        }

        $attendee_id = $attendee->id ?? null;
        $attendance = Attendance::where('event_id', '=', $event->id)->where('attendee_id', '=', $attendee_id)->whereDate('clocked_in_date', '=', Carbon::now()->format('Y-m-d'))->first();
        if (!$attendance)
        {
            $printNewTag = isset($attendee->Attendance) && $attendee->Attendance->count() == 0;
            if (!$attendee_id)
            {
                $attendee = new Attendee();
                $attendee->event = $event->id;
                $request->request->add(['event' => $event->id]);
                //Log::info(print_r($request->input(),true));
                $attendee = AttendeeService::setAttendeeRecords($request, $attendee);
                //Log::info(print_r($request->input(),true));
                if ($attendee->save())
                {
                    if( $event && $event->tag_image_option == 'qr_code') {
                        AttendeeService::generateQRCode($event, $attendee, $pin_code);
                    }
                    AttendeeEvent::Create(['event_id' => $attendee->event, 'attendee_id' => $attendee->id, 'pin_code' => $pin_code]);
                    $attendee_id = $attendee->id;
                }
            }

            if ($attendee_id)
            {
                $attendance = Attendance::Create(['event_id' => $event->id, 'attendee_id' => $attendee_id, 'clocked_in_date' => Carbon::now(), 'clocked_in_time' => Carbon::now(), 'mode' => $request->input('mode')]);
                if ($request->input('guest_show') == 'on')
                {
                    EventGuestAttendee::Create(['event_guest_id' => $request->input('guest_selected'), 'attendee_id' => $attendee_id]);
                }
            }
            $attendee_event = AttendeeEvent::with('event', 'attendee')->attendeeid($attendee_id)->first();

            //TODO put organizer logo in separate service
            $organizerLogo = (isset($event->Organizer->logo_filename)) ? asset(config('main.organizer_logo_dir') . '/medium.' . $event->Organizer->logo_filename) : '';
            $organizerLogo = (isset($event->cover_photo)) ? asset(config('main.cover_photo_dir') . '/medium.' . $event->cover_photo) : $organizerLogo;
                //Log::debug("organizerLogo: " . $organizerLogo);
            $otherData['attendee'] = $attendee;
            $otherData['event_obj'] = $event;
            if ($request->has('table_number') && $request->filled('table_number'))
            {
                $otherData['table_number'] = $request->input('table_number');
            }
            $otherData['location'] = $attendee->location;
            $otherData['event'] = $attendee->Event;
            $otherData['pin_code'] = $attendee->attendee_event->pin_code;


            if ($registration == 'pin')
            {
                if ($printNewTag)
                {
                    //Log::info(print_r($otherData['location_to_country'],true));
                    //Log::info(print_r($otherData['location'],true));
                    //dd($otherData['location']);
                    $this->printTag($attendee->attendee_event->pin_code, $attendee->full_name, $attendee->company, $organizerLogo, $attendee->attendee_event->pin_code, $otherData);
                }
            }
            else
            {

                if ($request->input('guest_show') == 'on')
                {
                    $otherData['guest_show'] = $request->input('guest_show');
                    $eventGuest = EventGuest::find($request->input('guest_selected'));
                    //Log::debug(print_r($eventGuest, true));
                    if ($eventGuest)
                    {
                        $otherData['table_number'] = $eventGuest['table_number'];
                    }
                    $this->printTag($attendee->attendee_event->pin_code, $attendee->full_name, $attendee->company, $organizerLogo, $attendee->attendee_event->pin_code, $otherData);
                    $this->printTag($attendee->attendee_event->pin_code, $attendee->full_name, $attendee->company, $organizerLogo, $attendee->attendee_event->pin_code . '.2', $otherData);
                }
                else
                {
                    $this->printTag($attendee->attendee_event->pin_code, $attendee->full_name, $attendee->company, $organizerLogo, $attendee->attendee_event->pin_code, $otherData);
                }

            }

            event(new AttendeeClockedIn($attendee_event));
            EventService::setAttendanceCache($event->id, $event->event_code);
            if ($registration == 'pin')
            {
                $attendee->mode = $request->input('mode');
                $attendee->save();
                return response()->json([
                    'status' => 'success',
                    'full_name' => $attendee->full_name,
                    'message' => 'Attendee record saved',
                ], 200);
            }

            return response()->json([
                'status' => 'success',
                'message' => 'Attendee record saved',
            ], 200);
        }
        else
        {
            return response()->json([
                'status' => 'error',
                'message' => 'User already registered for the day',
            ], 400);
        }

    }

    private function fixNull($data)
    {
        return collect($data)->map(function ($value, $key) {

resources/views/attendees/create.blade.php
@extends('layouts.app')
@section('title'){{'Attendees - Add New - '.config('app.name')}}@endsection
@section('content')
<div class="container-fluid">
    <div class="page-header">
        <h2>
            Attendees - Add New
        </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{route('dashboard')}}">
                    Dashboard
                </a>
            </li>
             <li>
                <a href="{{route('attendees.index')}}">
                    Attendees
                </a>
            </li>
            <li class="active">
                Add New
            </li>
        </ol>
    </div>
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="card">
                <div class="body">
                    <div class="row">
                        <form action="{{route('attendees.store')}}" class="" enctype="multipart/form-data" method="POST">
                            @include('attendees.form',['event_id'=>$event_id])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/attendees/edit.blade.php
@extends('layouts.app')
@section('title'){{'Attendees -  '.config('app.name')}}@endsection
@section('content')
<div class="container-fluid">
    <div class="page-header">
        <h2>
            Attendees - Edit [#{{$event->id}}]
        </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{route('dashboard')}}">
                    Dashboard
                </a>
            </li>
             <li>
                <a href="{{route('attendees.index')}}">
                    Attendees
                </a>
            </li>
            <li class="active">
                {{$attendee->full_name}}
            </li>
        </ol>
    </div>
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="card">
                <div class="body">
                    <div class="row">
                        <form action="{{route('attendees.update',['id'=>$attendee->id])}}" class="" enctype="multipart/form-data" method="POST">
                            <input type="hidden" name="_method" value="PUT">
                            @include('attendees.form',['event_id'=>$event_id])
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/attendees/index.blade.php
@extends('layouts.app')
@if($event)
    @section('title'){{$event->title.' - Attendees - '.config('app.name')}}@endsection
@else
    @section('title'){{'Attendees - '.config('app.name')}}@endsection
@endif

@section('content')
<div class="container-fluid">
    <div class="page-header">
        <h2>
            @if($event)
                Attendees
            <a class="btn btn-primary" href="{{route('attendees.create',['event'=>$event->id])}}">
                <i class="fa fa-plus">
                </i>
                Add New
            </a>
            @else
                Attendees
            <a class="btn btn-primary" href="{{route('attendees.create')}}">
                <i class="fa fa-plus">
                </i>
                Add New
            </a>
            @endif
            @if($event)
            <a href="{{route('attendees.import',['event'=>$event->id])}}" class="btn btn-success"><i class="fa fa-upload"></i> Import</a>
            @endif
            @if($event)
            <a href="{{route('attendees.export',['event'=>$event->id])}}" class="btn btn-success"><i class="fa fa-file-excel-o"></i> Export</a>
            @endif
            @if($event)
            <a href="{{route('attendees.clearall',['event'=>$event->id])}}" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete all {{$event->title}} attendees?');"><i class="fa fa-trash-o"></i> Clear All</a>
            @endif
        </h2>
        <ol class="breadcrumb">
            <li>
                <a href="{{route('dashboard')}}">
                    Dashboard
                </a>
            </li>
            <li>
                <a href="{{route('attendees.index')}}">
                    Attendees
                </a>
            </li>
            @if($event)
            <li class="active">
                {{$event->title}}
            </li>
            @endif
        </ol>
    </div>
    <div class="row clearfix">
        <div class="col-md-12">
            <div class="card">
                @if($event)
                <div class="card-header">
                    <h2>
                        {{$event->title.' - Attendees'}}
                    </h2>
                </div>
                @endif
                <div class="body">
                    @include('flash::message')
                    <div class="row">
                        <!--Advanced Search-->
                        <div class="col-md-12">
                        </div>
                        <!--#Advanced Search-->
                        <div class="table table-responsive">
                            @php
                                $formFields=['full_name'=>'Full Name','phone'=>'Phone','email'=>'Email','company'=>'Company','position'=>'Position','gender'=>'Gender','age'=>'Age','location'=>'Location','country'=>'Country','level_education'=>'Highest Level of Education','lived_abroad'=>'Lived Abroad (6 months above)','attending_as'=>'Attending As'];
                            @endphp
                        <table class="table table-striped ">
                            <thead>
                                <tr>
                                    <th>
                                        Pin Code
                                    </th>
                                    @foreach($formFields as $formKey =>$formLabel)
                                        @if($event['app_field_'.$formKey] ==='on')
                                            <th>{{ $formLabel }}</th>
                                        @endif
                                    @endforeach
                                    <th>
                                        Created
                                    </th>
                                    <th colspan="2">
                                        Action
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($attendees as $attendee)
                                <tr>
                                    <td>
                                        {{$attendee->attendee_event->pin_code ?? ''}}
                                    </td>
                                    @foreach($formFields as $formKey =>$formLabel)
                                        @if($event['app_field_'.$formKey] ==='on')
                                            @if($formKey === 'country')
                                                @php
                                                    $countries = config('countries');
                                                @endphp
                                                <td>{{ (!empty($attendee[$formKey])) ? $countries[$attendee[$formKey]] : 'N/A'  }}</td>
                                            @else
                                                <td>{{ (!empty($attendee[$formKey]) &&  ($attendee[$formKey]!= 'null')) ? $attendee[$formKey] : 'N/A' }}</td>
                                            @endif
                                        @endif
                                    @endforeach
                                    <td>
                                        {{$attendee->created_at->format('d M ,Y h:ia')}}
                                    </td>
                                    @isset($attendee->attendee_event->pin_code)
                                    <td>
                                        <a class="btn btn-default" target="_blank" href="{{ asset(config('main.qr_code_dir') . '/' . $attendee->attendee_event->pin_code  .'.png') }}" title="View QR Code">
                                            <i class="fa fa-qrcode">
                                            </i>
                                        </a>
                                    </td>
                                    @endisset
                                    <td>
                                        <a class="btn btn-default" href="{{ route('attendees.show',$attendee->id) }}" title="View">
                                            <i class="fa fa-eye">
                                            </i>
                                        </a>
                                    </td>
                                    <td>
                                        <a class="btn btn-warning" href="{{ route('attendees.edit',$attendee->id) }}" title="Edit">
                                            <i class="fa fa-edit">
                                            </i>
                                        </a>
                                    </td>
                                    {{--
                                    <td>
                                        <form action="{{ route('attendees.destroy',['id'=>$attendee->id]) }}" method="post">
                                            @csrf
                                            <input name="_method" type="hidden" value="DELETE">
                                                <button class="btn btn-danger" title="Delete" type="submit">
                                                    <i class="fa fa-trash">
                                                    </i>
                                                </button>
                                            </input>
                                        </form>
                                        --}}
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                        </div>
                        @if(!$event)
                        <div class="col-md-12">
                            Showing {{($attendees->currentpage()-1)* $attendees->perpage()+1}} to {{(($attendees->currentpage()-1) * $attendees->perpage())+$attendees->count()}} of {{$attendees->total()}} entries
                        </div>
                        <div class="pull-right">
                            {{ $attendees->links() }}
                        </div>
                        @endif
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection